my_list=[1,2,3,4]
my_list.reverse()
print(my_list)


#except Exception as e = eccetto ci sia un errore errore-->allora fai questo
#e=istanza di value error
#le eccezioni sono gerarchiche (prima exception, poi le altre)

#